in:
  type: file
  path_prefix: /Users/devlop/github/embulk-filter-lonlat/data/test.csv
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    columns:
    - {name: status, type: string}
    - {name: address, type: string}
    - {name: lat, type: double}
    - {name: lon, type: double}
filters:
  - type: column
    drop_columns:
      - {name: status}
#  - type: url_encode
#    column: address
  - type: lonlat
    lat_columns:
      - {name: lat, type: lat, format: MSEC, datum: WGS84}
    lon_columns:
      - {name: lon, type: lon, format: MSEC, datum: WGS84}
out: {type: stdout}